child:
  claiming:
    enabled: true
    rooms: __NETDATA_CLAIM_ROOM__
    token: __NETDATA_CLAIM_TOKEN__
  configs:
    netdata:
      data: |
        [db]
          mode = ram
        [web]
          bind to = 0.0.0.0:19999
        [health]
          enabled = no
        [ml]
          enabled = no
    stream:
      data: |
        [stream]
          enabled = yes
          destination = netdata-parent:19999
          api key = __STREAMING_API_KEY__
          timeout seconds = 60
          buffer size bytes = 1048576
          reconnect delay seconds = 5
          initial clock resync iterations = 60
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 900Mi
    requests:
      cpu: 100m
      memory: 300Mi
image:
  repository: netdata/netdata
  tag: v2.6.3
  pullPolicy: IfNotPresent  
ingress:
  enabled: false
parent:
  claiming:
    enabled: true
    rooms: __NETDATA_CLAIM_ROOM__
    token: __NETDATA_CLAIM_TOKEN__
  enabled: false
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 10Gi
    storageClass: ""
podSecurityContext: {}
restarter:
  enabled: false
  image:
    repository: alpine/k8s
    tag: "1.35.6"
