apiVersion: v1
kind: Service
metadata:
  name: netdata-child-svc
  namespace: netdata
spec:
  selector:
    app: netdata # Match the label of your Netdata child pods
    role: child  
  ports:
    - protocol: TCP
      port: 19999
      targetPort: 19999
