apiVersion: v1
kind: Service
metadata:
  name: netdata-master-svc
  namespace: netdata
spec:
  clusterIP: None  # This makes it a Headless Service
  selector:
    # Match the specific pod label for the master node
    # You'll need to define this label in the master pod's YAML
    app: netdata-master
  ports:
    - protocol: TCP
      port: 19999
      targetPort: 19999
