apiVersion: v1
kind: Service
metadata:
  name: netdata-parent-service
  namespace: netdata
spec:
  selector:
    app: netdata
    component: parent
  ports:
    - protocol: TCP
      port: 19999
      targetPort: 19999
  type: ClusterIP
