apiVersion: v1
kind: ConfigMap
metadata:
  name: minimal-api-nginx-config
  namespace: netdata
data:
  default.conf: |
    server {
      listen 80;

      add_header "Access-Control-Allow-Origin" "*" always;

      location = / {
        add_header Content-Type text/plain;
        return 200 "Multi-Node API: /master/cpu, /worker1/cpu, /worker2/cpu";
      }

      location /master/cpu {
        proxy_pass http://10.244.0.40:19999/api/v1/data?chart=system.cpu&format=json;
        proxy_set_header Host $host;
        proxy_connect_timeout 5s;
      }
      
      location /master/memory {
        proxy_pass http://10.244.0.40:19999/api/v1/data?chart=system.ram&format=json;
        proxy_set_header Host $host;
        proxy_connect_timeout 5s;
      }

      location /worker1/cpu {
        proxy_pass http://192.168.4.101:19999/api/v1/data?chart=system.cpu&format=json;
        proxy_set_header Host $host;
        proxy_connect_timeout 5s;
      }

      location /worker1/memory {
        proxy_pass http://192.168.4.101:19999/api/v1/data?chart=system.ram&format=json;
        proxy_set_header Host $host;
        proxy_connect_timeout 5s;
      }
      
      location /worker2/cpu {
        proxy_pass http://192.168.4.102:19999/api/v1/data?chart=system.cpu&format=json;
        proxy_set_header Host $host;
        proxy_connect_timeout 5s;
      }

      location /worker2/memory {
        proxy_pass http://192.168.4.102:19999/api/v1/data?chart=system.ram&format=json;
        proxy_set_header Host $host;
        proxy_connect_timeout 5s;
      }
    }
