apiVersion: v1
data:
  go.d: |
    modules:
      pulsar: no
      prometheus: yes
  kubelet: |
    update_every: 1
    autodetection_retry: 0
    jobs:
      - name: local
        url: http://127.0.0.1:10255/metrics
      - name: local
        url: https://localhost:10250/metrics
        tls_skip_verify: yes
  kubeproxy: |
    update_every: 1
    autodetection_retry: 0
    jobs:
      - name: local
        url: http://127.0.0.1:10249/metrics
  netdata: |
    [db]
      mode = ram
    [web]
      bind to = localhost:19999
    [health]
      enabled = no
    [ml]
      enabled = no
  stream: |
    [stream]
      enabled = yes
      destination = netdata:19999
      api key = 11111111-2222-3333-4444-555555555555
      timeout seconds = 60
      buffer size bytes = 1048576
      reconnect delay seconds = 5
      initial clock resync iterations = 60
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: netdata
    meta.helm.sh/release-namespace: netdata
  creationTimestamp: "2025-08-27T16:11:22Z"
  labels:
    app: netdata
    app.kubernetes.io/managed-by: Helm
    chart: netdata-3.7.145
    heritage: Helm
    release: netdata
  name: netdata-conf-child
  namespace: netdata
  resourceVersion: "803048"
  uid: b48935f0-9ef4-4b41-8dc6-58fc7a7cbc46
