apiVersion: v1
kind: Service
metadata:
  name: netdata-minimal-api
  namespace: netdata
spec:
  selector:
    app: netdata-minimal-api
  ports:
    - protocol: TCP
      port: 8080      # This must match the ingress port
      targetPort: 80  # This matches the nginx container port
      name: http
  type: ClusterIP
